apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers: # Level 1
      - name: mysql # Level 2 (pake strip)
        image: mysql:8.0
        env:        # Level 3 (HARUS menjorok ke dalam 'name: mysql')
        - name: MYSQL_DATABASE
          value: laravel_k8s
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306